W6D5/nineninecats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats
end

W6D5/nineninecats/app/models/cat.rb
class Cat < ApplicationRecord

    CAT_COLORS = ['Orange', 'Black', 'Brown', 'White', 'Gray']

    validates :birth_date, presence: true
    validates :color, presence: true, inclusion: { in: CAT_COLORS }
    validates :name, presence: true
    validates :sex, presence: true
    validates :description, presence: true

    
end

W6D5/nineninecats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end


end

W6D5/nineninecats/app/views/cats/_cat.html.erb
<li>Name: <%=cat.name %></li>
<li>Birth date: <%=cat.birth_date %></li>
<li>Sex: <%=cat.sex %></li>
<li>Color: <%=cat.color %></li>
<li>Description: <%=cat.description %></li>

W6D5/nineninecats/app/views/cats/index.html.erb
<h1> Look at all these Cats! </h1>

<ul>
    <%@cats.each do |cat| %>
    <ul>
        <a href="<% cat_url(cat.id) %>"> <%=cat.name %></a>
        <br/>
    </ul>
    <% end %>
</ul>

W6D5/nineninecats/app/views/cats/show.html.erb
<table style="width: 15%">
    <thead>
        <tr>
            <th colspan="2"> <%= @cat.name %> </th> 
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>Attribute</th>
            <th>Value</th>
        </tr>
        <tr>
            <td>Birth Date</td>
            <td><%= @cat.birth_date %></td>
        </tr>
        <tr>
            <td>Color</td>
            <td><%= @cat.color%></td>
        </tr>
        <tr>
            <td>Sex</td>
            <td><%= @cat.sex %></td>
        </tr>
    </tbody>
</table>

<a href="<%= cats_url %>">Back to the index!</a>

W6D5/nineninecats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nineninecats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>